title: João Oliveira
email: lucas.xms@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um lugar para se falar de Python, Data Science, Machine Learning e Estatística
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_username: joaolso

permalink: /:title/

kramdown:
  hard_wrap: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  